# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 06064d81c193d6701eb72868412324076a10bdbf29b184ff4dacd3cb0e8cc55d3e179e9c003a2dc845d6ce964b753298522e90146c22509a2e8ccc47ceaddd66

test:
  secret_key_base: 4e71efcf1580a2352d18a32aacdd770168d3398d6808d97906ffee468a26a4c0e2a546f8ecee5da5ed4580b68023107f57e754fecb7b37683f5d03bc5122ae86

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
